repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        args: ["--maxkb=5000"]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: name-tests-test
      - id: requirements-txt-fixer
      - id: pretty-format-json
        args: ["--indent=6"]
      - id: requirements-txt-fixer # Sorts entries in requirements.txt
      - id: forbid-new-submodules # Check for git submodules
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.6.4
    hooks:
      - id: isort
